### ISSUE TITLE
No index error if param index is out range.

### ISSUE THREAD

**Issue by Viatorus** [jhonmart/python-format-js#32]
**Describe the bug**
No index error if param index is out range.

**To Reproduce**
```js
"{}".format();
```
Results in `undefined`.

**Expected behavior**

`IndexError: Replacement index 0 out of range for positional args tuple`

**Comment by romulo94** [comment]
@Viatorus  I'll investegate!

**Comment by jhonmart** [comment]
### I would like to thank you for your contribution.You, with that, now helped more than a thousand developers. @Viatorus

**Comment by Viatorus** [comment]
Very charming. ;)
Thank you too.
