### ISSUE TITLE
Fill with trailing zeros is missing 

### ISSUE THREAD

**Issue by mazito** [jhonmart/python-format-js#41]
The parameter  `0` used to fill the output with trailing zeros is not supported, though it is valid Python, as can be seen in example below:
~~~
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> fs = "{:03d}"
>>> print(fs.format(7))
007
>>> 
~~~

**To Reproduce**
~~~
const r = "{:03d}".format(7);
~~~
The result should be `007`

**Comment by jhonmart** [comment]
### I would like to thank you for your contribution. You with that, make a world with fewer bugs. @mazito
