### ISSUE TITLE
Problem with formatting

### ISSUE THREAD

**Issue by shooter01** [jhonmart/python-format-js#42]
The code
```
const format = require("python-format-js");

const line_parts = ['001 {0: >7}  {1:74.1f}     '.format(1, '3.0')]
line_parts.push('{0: >9} {1} {2}'.format(3, 'w', 1))
line_parts.push('\n')
console.log(line_parts.join(''));
```
gives me 

![Screenshot from 2021-09-19 11-54-14](https://user-images.githubusercontent.com/47353294/133921455-52f84993-2e1b-49c6-b286-35855322e355.png)

but I expect
![Screenshot from 2021-09-19 11-48-51](https://user-images.githubusercontent.com/47353294/133921372-a3c20638-1cb3-42f3-a887-e90e89333648.png)

**Comment by jhonmart** [comment]
### I would like to thank you for your contribution. I made some fixes and improvements regarding this. You keep the community growing. @shooter01
