### ISSUE TITLE
Throws on 0 argument for field {:<3}

### ISSUE THREAD

**Issue by CarstenNZ** [jhonmart/python-format-js#48]
**Disclaimer**
I'm new to TS/JS and copied your string prototype format to an old-style function (pyFmt). 
This shouldn't change the behavior.

**Thanks for writing this package, I always thought format strings are standard since Kernighan & Ritchie (1977) ;)** 
and your package makes my life easier

**Describe the bug**
Throws on 0 argument for field {:<3}

**To Reproduce**
- for you: `"@{}/{:<3}".format(37032656, 0)`
- on my variant: `pyFormat("@{}/{:<3}", 37032656, 0)`

**Reason**
Line 40 ` if (!ACTUAL_VALUE)` is true for 0 and should be probably something like
`if (ACTUAL_VALUE === null || ACTUAL_VALUE === undefined)`.
You will now better

**Possible improvements**
- provide and alternative/additional old-style function interface
- document how to simply import into TS (I struggled and would prefer to import your package unmodified)
- add actual arguments to your error string in line 42,  
   I use `pyFormat("${fmtStr}", ${args_.map((o: any) => String(o)).join(',')})`

**Comment by jhonmart** [comment]
I apologize for the delay in providing updates on these points. I've now incorporated TypeScript into the project and resolved the identified bug. Additionally, I've created tests to ensure the application's stability. Thank you for your patience and understanding during this process. If you have any further questions or need additional assistance, please feel free to ask.

Feel free to personalize it further or let me know if you need any additional information!

#49 
I would like to thank you for your contribution. You with that, make a world with fewer bugs. @CarstenNZ
